// Regenerate with: npm install --no-save sharp && node scripts/portraits/generate.mjs
import fs from "fs";
import path from "path";
import sharp from "sharp";
import { SPECS } from "./specs.mjs";
import { renderPortrait } from "./engine.mjs";

const root = path.resolve(import.meta.dirname, "../..");
const outDir = path.join(root, "public/portraits");
fs.mkdirSync(outDir, { recursive: true });

const dataSlugs = new Set();
for (const file of ["people-gods.ts", "people-others.ts", "people-mortals.ts", "people-creatures.ts"]) {
  const text = fs.readFileSync(path.join(root, "data", file), "utf8");
  for (const match of text.matchAll(/slug: "([^"]+)"/g)) dataSlugs.add(match[1]);
}
const specSlugs = SPECS.map((s) => s.slug);
const specSet = new Set(specSlugs);
if (specSlugs.length !== specSet.size) throw new Error("Duplicate portrait spec");
for (const slug of dataSlugs) {
  if (!specSet.has(slug)) throw new Error(`Missing portrait spec: ${slug}`);
}
for (const slug of specSet) {
  if (!dataSlugs.has(slug)) throw new Error(`Extra portrait spec: ${slug}`);
}

const only = process.argv.slice(2);
const jobs = only.length ? SPECS.filter((s) => only.includes(s.slug)) : SPECS;

for (const spec of jobs) {
  const svg = renderPortrait(spec);
  await sharp(Buffer.from(svg)).webp({ quality: 82 }).toFile(path.join(outDir, `${spec.slug}.webp`));
}

if (!only.length) {
  const body = specSlugs
    .map((slug) => {
      const spec = SPECS.find((s) => s.slug === slug);
      return `  ${JSON.stringify(slug)}: { src: ${JSON.stringify(`/portraits/${slug}.webp`)}, alt: ${JSON.stringify(spec.alt)} },`;
    })
    .join("\n");
  const ts = `/** Generated by scripts/portraits/generate.mjs. Illustrated portraits, one per person slug. */\nexport const portraits: Record<string, { src: string; alt: string }> = {\n${body}\n};\n`;
  fs.writeFileSync(path.join(root, "data/portraits.ts"), ts);

  const thumbs = [];
  const cols = 11;
  const tw = 132;
  const th = 176;
  for (let i = 0; i < SPECS.length; i++) {
    const buf = await sharp(path.join(outDir, `${SPECS[i].slug}.webp`)).resize(tw, th).toBuffer();
    thumbs.push({ input: buf, left: (i % cols) * tw, top: Math.floor(i / cols) * th });
  }
  const rows = Math.ceil(SPECS.length / cols);
  await sharp({ create: { width: cols * tw, height: rows * th, channels: 3, background: "#faf7f0" } })
    .composite(thumbs)
    .webp({ quality: 80 })
    .toFile("/tmp/portraits-sheet.webp");
}

console.log(`wrote ${jobs.length} portraits (${dataSlugs.size} slugs)`);
